# Generated by Django 2.1 on 2018-08-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auv_id', models.UUIDField(blank=True, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=1024)),
                ('update_frequency', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('left_motor_channel', models.IntegerField(default=0)),
                ('right_motor_channel', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('crossbar_url', models.CharField(default='ws://localhost:8000/ws', max_length=255)),
                ('crossbar_realm', models.CharField(default='realm1', max_length=255)),
            ],
            options={
                'verbose_name': 'AUV Configuration',
            },
        ),
    ]
