# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AUVConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=1024)),
                ('update_frequency', models.DecimalField(decimal_places=3, max_digits=5)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'AUV Configuration',
            },
        ),
    ]
