# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auv_control_pi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auvconfiguration',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auvconfiguration',
            name='auth_token',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='auvconfiguration',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auvconfiguration',
            name='update_frequency',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
