# Generated by Django 2.1 on 2018-11-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auv_control_pi', '0002_auto_20181101_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='kD',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='kI',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='kP',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='configuration',
            name='pid_error_debounce',
            field=models.FloatField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='configuration',
            name='target_waypoint_distance',
            field=models.FloatField(blank=True, default=60),
        ),
    ]
