# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auv_control_pi', '0002_auto_20160925_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(blank=True, max_length=1024)),
                ('update_frequency', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('left_motor_channel', models.IntegerField(default=0)),
                ('right_motor_channel', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'AUV Configuration',
            },
        ),
        migrations.DeleteModel(
            name='AUVConfiguration',
        ),
    ]
