# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auv_control_pi', '0003_auto_20161002_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='auv_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
