# Generated by Django 2.1 on 2018-11-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auv_control_pi', '0003_auto_20181110_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='declination',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='magbias_x',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='magbias_y',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='magbias_z',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
