# Generated by Django 2.1 on 2018-11-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auv_control_pi', '0004_auto_20181111_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='board_offset',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
