# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auv_control_pi', '0005_auto_20161022_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='crossbar_url',
            field=models.CharField(default='ws://localhost:8080/ws', max_length=255),
        ),
    ]
