# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-08-11 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auv_control_pi', '0006_auto_20161022_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='crossbar_url',
            field=models.CharField(default='ws://localhost:8000/ws', max_length=255),
        ),
    ]
